---
- name: checkout rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv accept_hostkey=yes

- name: checkout ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: create .bash.d directory
  file: path=~/.bash.d state=directory owner={{ ruby_deploy_user }} group={{ ruby_deploy_user }} mode=0755

- name: set rbenv.bash
  copy: src=rbenv.bash dest=~/.bash.d/rbenv.bash mode=700 owner={{ ruby_deploy_user }}

- name: add source rbenv.bash to bash_profile
  lineinfile: dest=~/.bash_profile regexp="rbenv" insertafter=EOF line="source ~/.bash.d/rbenv.bash" create=yes

- name: source .bash_profile
  shell: source ~/.bash_profile

- name: check ruby is already installed
  shell: cd; bash -lc "rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
  register: ruby_is_installed

- name: install ruby
  shell: cd; bash -lc "CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ ruby_version }}"
  when: ruby_is_installed.stdout != '{{ ruby_version }}'
  async: 600
  poll: 30

- name: rbenv global
  shell: cd; bash -lc "rbenv global {{ ruby_version }}"

- name: install bundler gem
  gem: name=bundler state=present executable=.rbenv/shims/gem user_install=False
